POST http://localhost:8080/api/folders/
Content-type :application/json

{"name": "testPostFoldur"}

# {"title": "csss:D:D","description": "testDesc:D", "deadline": "2018-11-09 01:25:30", "folder_id": 1}

###
### ?sorted=desc&by=timeCreated  
GET http://localhost:8080/api/tasks?sorted=asc&by=id
### 

DELETE http://localhost:8080/api/folders/8